export const API_ERROR_CODE = {
  ACTION_INVALID: "ACTION_INVALID",
  ACCOUNT_DELETE_REQUIRES_SOLO_OWNERSHIP: "ACCOUNT_DELETE_REQUIRES_SOLO_OWNERSHIP",
  CHORE_NOT_FOUND: "CHORE_NOT_FOUND",
  CANCEL_SCOPE_INVALID: "CANCEL_SCOPE_INVALID",
  DELETE_TOKEN_INVALID: "DELETE_TOKEN_INVALID",
  EMAIL_REQUIRED: "EMAIL_REQUIRED",
  FORBIDDEN: "FORBIDDEN",
  HOUSEHOLD_HAS_OTHER_MEMBERS: "HOUSEHOLD_HAS_OTHER_MEMBERS",
  HOUSEHOLD_NAME_REQUIRED: "HOUSEHOLD_NAME_REQUIRED",
  HOUSEHOLD_NOT_FOUND: "HOUSEHOLD_NOT_FOUND",
  HOUSEHOLD_REQUIRED: "HOUSEHOLD_REQUIRED",
  HOUSEHOLD_SELECTION_REQUIRED: "HOUSEHOLD_SELECTION_REQUIRED",
  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
  INVALID_INVITE: "INVALID_INVITE",
  INVALID_JSON_BODY: "INVALID_JSON_BODY",
  INVALID_TIME_ZONE: "INVALID_TIME_ZONE",
  INVALID_TOKEN_IDENTIFIER: "INVALID_TOKEN_IDENTIFIER",
  INVALID_USER: "INVALID_USER",
  LAST_OWNER_REQUIRED: "LAST_OWNER_REQUIRED",
  MEMBER_NOT_FOUND: "MEMBER_NOT_FOUND",
  MISSING_CHORE_OCCURRENCE: "MISSING_CHORE_OCCURRENCE",
  NAME_REQUIRED: "NAME_REQUIRED",
  OCCURRENCE_OUTSIDE_SCHEDULE: "OCCURRENCE_OUTSIDE_SCHEDULE",
  OCCURRENCE_CANCELED: "OCCURRENCE_CANCELED",
  OWNER_ROLE_MANAGEMENT_FORBIDDEN: "OWNER_ROLE_MANAGEMENT_FORBIDDEN",
  PENDING_INVITE_NOT_FOUND: "PENDING_INVITE_NOT_FOUND",
  SELF_MEMBER_REMOVAL_FORBIDDEN: "SELF_MEMBER_REMOVAL_FORBIDDEN",
  SELF_ROLE_CHANGE_FORBIDDEN: "SELF_ROLE_CHANGE_FORBIDDEN",
  STATUS_INVALID: "STATUS_INVALID",
  UNAUTHORIZED: "UNAUTHORIZED",
  UNDO_WINDOW_EXPIRED: "UNDO_WINDOW_EXPIRED",
  USER_ALREADY_IN_HOUSEHOLD: "USER_ALREADY_IN_HOUSEHOLD",
  USER_ALREADY_INVITED: "USER_ALREADY_INVITED",
  USER_IN_OTHER_HOUSEHOLD: "USER_IN_OTHER_HOUSEHOLD",
  USER_NOT_FOUND: "USER_NOT_FOUND",
  VALIDATION_FAILED: "VALIDATION_FAILED",
} as const;

export type ApiErrorCode = (typeof API_ERROR_CODE)[keyof typeof API_ERROR_CODE];

type ApiErrorPayload = {
  code: ApiErrorCode;
  error: string;
};

export const apiErrorBody = <T extends Record<string, unknown>>(payload: ApiErrorPayload & T) => {
  return {
    ok: false as const,
    ...payload,
  };
};

export const jsonError = <T extends Record<string, unknown>>({
  headers,
  status,
  ...payload
}: {
  headers?: HeadersInit;
  status: number;
} & ApiErrorPayload &
  T) => {
  return Response.json(apiErrorBody(payload), { status, headers });
};
